-- TrendSurfer Schema (TRD v1.0 based)

-- 1. stocks (종목 마스터)
CREATE TABLE IF NOT EXISTS stocks (
    ticker VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    market VARCHAR(10) NOT NULL, -- KOSPI / KOSDAQ
    sector VARCHAR(100),
    is_preferred BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments for stocks table
COMMENT ON TABLE stocks IS '종목 마스터 정보';
COMMENT ON COLUMN stocks.ticker IS '종목 코드 (PK)';
COMMENT ON COLUMN stocks.name IS '종목명';
COMMENT ON COLUMN stocks.market IS '시장 구분 (KOSPI/KOSDAQ)';
COMMENT ON COLUMN stocks.sector IS '업종/섹터';
COMMENT ON COLUMN stocks.is_preferred IS '우선주 여부 (True: 우선주)';
COMMENT ON COLUMN stocks.is_active IS '거래 가능 여부 (False: 상장폐지 등)';
COMMENT ON COLUMN stocks.created_at IS '생성 일시';
COMMENT ON COLUMN stocks.updated_at IS '수정 일시';


-- 2. daily_candles (일봉 데이터)
CREATE TABLE IF NOT EXISTS daily_candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL REFERENCES stocks(ticker) ON DELETE CASCADE,
    date DATE NOT NULL,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume BIGINT,
    amount NUMERIC, -- 거래대금
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- 인덱스: 종목별 날짜 조회 성능 향상
    CONSTRAINT daily_candles_ticker_date_unique UNIQUE (ticker, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_candles_ticker_date ON daily_candles(ticker, date DESC);

-- Comments for daily_candles table
COMMENT ON TABLE daily_candles IS '일봉(Daily Candle) 데이터';
COMMENT ON COLUMN daily_candles.id IS '일봉 데이터 PK';
COMMENT ON COLUMN daily_candles.ticker IS '종목 코드 (FK)';
COMMENT ON COLUMN daily_candles.date IS '거래 일자';
COMMENT ON COLUMN daily_candles.open IS '시가';
COMMENT ON COLUMN daily_candles.high IS '고가';
COMMENT ON COLUMN daily_candles.low IS '저가';
COMMENT ON COLUMN daily_candles.close IS '종가';
COMMENT ON COLUMN daily_candles.volume IS '거래량';
COMMENT ON COLUMN daily_candles.amount IS '거래대금';
COMMENT ON COLUMN daily_candles.created_at IS '생성 일시';


-- 3. daily_technical_indicators (기술적 지표)
CREATE TABLE IF NOT EXISTS daily_technical_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL REFERENCES stocks(ticker) ON DELETE CASCADE,
    date DATE NOT NULL,
    
    -- Moving Averages
    ma_5 NUMERIC,
    ma_20 NUMERIC,
    ma_60 NUMERIC,
    ma_120 NUMERIC,
    
    -- RSI
    rsi_14 NUMERIC,
    
    -- MACD
    macd NUMERIC,
    macd_signal NUMERIC,
    macd_hist NUMERIC,
    
    -- Bollinger Bands
    bb_upper NUMERIC,
    bb_middle NUMERIC,
    bb_lower NUMERIC,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    CONSTRAINT daily_tech_ind_ticker_date_unique UNIQUE (ticker, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_tech_ticker_date ON daily_technical_indicators(ticker, date DESC);

-- Comments for daily_technical_indicators table
COMMENT ON TABLE daily_technical_indicators IS '일봉 기반 기술적 지표 데이터';
COMMENT ON COLUMN daily_technical_indicators.id IS '지표 데이터 PK';
COMMENT ON COLUMN daily_technical_indicators.ticker IS '종목 코드 (FK)';
COMMENT ON COLUMN daily_technical_indicators.date IS '기준 일자';
COMMENT ON COLUMN daily_technical_indicators.ma_5 IS '5일 이동평균';
COMMENT ON COLUMN daily_technical_indicators.ma_20 IS '20일 이동평균';
COMMENT ON COLUMN daily_technical_indicators.ma_60 IS '60일 이동평균';
COMMENT ON COLUMN daily_technical_indicators.ma_120 IS '120일 이동평균';
COMMENT ON COLUMN daily_technical_indicators.rsi_14 IS '14일 RSI';
COMMENT ON COLUMN daily_technical_indicators.macd IS 'MACD';
COMMENT ON COLUMN daily_technical_indicators.macd_signal IS 'MACD Signal';
COMMENT ON COLUMN daily_technical_indicators.macd_hist IS 'MACD Histogram';
COMMENT ON COLUMN daily_technical_indicators.bb_upper IS '볼린저 밴드 상단';
COMMENT ON COLUMN daily_technical_indicators.bb_middle IS '볼린저 밴드 중심';
COMMENT ON COLUMN daily_technical_indicators.bb_lower IS '볼린저 밴드 하단';
COMMENT ON COLUMN daily_technical_indicators.created_at IS '생성 일시';

-- 업데이트 시간 자동 갱신을 위한 함수 및 트리거 (선택사항)
-- CREATE OR REPLACE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--    NEW.updated_at = now();
--    RETURN NEW;
-- END;
-- $$ language 'plpgsql';

-- CREATE TRIGGER update_stocks_updated_at
-- BEFORE UPDATE ON stocks
-- FOR EACH ROW
-- EXECUTE PROCEDURE update_updated_at_column();
